reviewers:
  defaults:
    - Kgeek33

  per_author:
    Kgeek33:
      - Skyniraph
      - Lascar-png

    SaiKido33:
      - Kgeek33
      - Lascar-png
      - Skyniraph

files:
  ".github/**":
    - Kgeek33
  "Arbres/**":
    - SaiKido33
  "Bases de Données/**":
    - Lascar-png
  "Circuits Intégrés/**":
    - Kgeek33
  "Diviser pour Régner/**":
    - Skyniraph
  "Entraînement Pratique/**":
    - Kgeek33
  "Grand Oral/**":
    - Kgeek33
  "Les Graphes/**":
    - Skyniraph
  "Listes Chainées/**":
    - Kgeek33
  "Modularité/**":
    - SaiKido33
  "Piles et Files/**":
    - Lascar-png
  "Processus et Ressources/**":
    - Lascar-png
  "Programmation Orientée Objet/**":
    - SaiKido33
  "Protocoles de Routages/**":
    - Lascar-png
  "Récursivité/**":
    - Skyniraph
  "Sécurisation des Communications/**":
    - Lascar-png
  "TD Snake/**":
    - Skyniraph

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
