name: 👀 Auto Assign Reviewers

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2

    - name: 👀 Read reviewer configuration
      id: read-config
      run: |
        reviewers=$(yq e '.[] | .[] | .reviewver' .github/reviewer.yml | sort | uniq)
        echo "reviewers=$reviewers" >> $GITHUB_ENV

    - name: 📝 Get changed files
      id: get-changed-files
      run: |
        git fetch origin
        files=$(git diff --name-only origin/main..origin/${{ github.head_ref }})
        echo "changed_files=$files" >> $GITHUB_ENV

    - name: 🔄 Assign author and reviewers
      if: env.changed_files != ''
      run: |
        PR_AUTHOR="${{ github.event.pull_request.user.login }}"
        gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }} \
            -X PATCH -f assignees[]="$PR_AUTHOR"

        for file in $changed_files; do
          for reviewer in $reviewers; do
            if yq e ".[] | .[] | select(.\"any-glob-to-any-file\" == \"$file\") | .reviewver" .github/reviewer.yml | grep -q $reviewer; then
              gh pr review --add $reviewer
            fi
          done
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}