name: 🆕 Create a PR for creating a branch

on:
  create:

jobs:
  create-draft-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Check that the ref is a branch and not main
        id: check_branch
        run: |
          if [ "$GITHUB_REF_TYPE" != "branch" ]; then
            echo "Ce n'est pas une branche, on arrête."
            exit 78
          fi
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            echo "On ne crée pas de PR pour la branche main."
            exit 78
          fi
      - name: Create a request in draft
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          draft: true
          title: "${{ github.ref_name }} => main"
          body: "Pull request automatique pour la branche ${{ github.ref_name }}."
