name: 🆕 Créer une PR à la création d'une branche

on:
  create:
    branches:
      - '*'

jobs:
  create-draft-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier que la branche n'est pas main
        id: check_branch
        run: |
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            echo "On ne crée pas de PR pour la branche main."
            exit 78
          fi
      - name: Créer une Pull Request en draft
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref_name }}
          draft: true
          title: "${{ github.ref_name }} => main"
          body: "Pull request automatique pour la branche ${{ github.ref_name }}."
