name: 📝 Auto Tag on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  autotag:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v2

      - name: 🔍 Get changed files
        id: get_files
        run: |
          git fetch origin
          git diff --name-status origin/main..origin/${{ github.head_ref }} \
            | sed -E 's/^[A-Z]+\t//g' > modified_files.txt
          cat modified_files.txt

      - name: 🔖 Determine labels
        id: determine_labels
        run: |
          declare -A labels
          labels=(
            ["Arbres"]="Arbres"
            ["Bases de Donn\303\251es"]="Bases de Données"
            ["Circuits Int\303\251gr\303\251s"]="Circuits Intégrés"
            ["Entra\303\256nement Pratique"]="Epreuves pratiques"
            ["Listes Chain\303\251es"]="Listes Chainées"
            ["Modularit\303\251"]="Modularité"
            ["Piles et Files"]="Piles et Files"
            ["Programmation Orient\303\251e Objet"]="Programmation Orientée Objet"
            ["R\303\251cursivit\303\251"]="Récursivité"
            ["TD 50Capytale51"]="TD (Capytale)"
            ["TD Snake"]="TD Snake"
          )

          PR_LABELS=()

          while IFS= read -r file; do
            for folder in "${!labels[@]}"; do
              if [[ "$file" == *"$folder/"* ]]; then
                PR_LABELS+=("${labels[$folder]}")
              fi
            done
          done < modified_files.txt

          UNIQUE_LABELS=$(echo "${PR_LABELS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ',' | sed 's/,$//')
          echo $UNIQUE_LABELS

          echo "labels=$UNIQUE_LABELS" >> $GITHUB_ENV

      - name: 🏷️ Add labels to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.labels }}
