name: 🛠️ Update Contributors in README

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@v4.2.2

      - name: 📥 Fetch contributors from GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}
        run: |
          contributors=$(gh api repos/${{ github.repository }}/contributors --paginate)
          if [ -f .github/previous_contributors.json ]; then
            previous_contributors=$(cat .github/previous_contributors.json)
          else
            previous_contributors="{}"
          fi

          table="## Contributions des Contributeurs\n\n| Contributeur | Contributions | Évolution |\n|--------------|---------------|-----------|\n"
          bot_contributions=0

          for row in $(echo "$contributors" | jq -c '.[]'); do
            login=$(echo "$row" | jq -r '.login')
            contributions=$(echo "$row" | jq -r '.contributions')
            
            if [ "$login" = "github-actions[bot]" ] || [ "$login" = "actions-user" ]; then
              bot_contributions=$((bot_contributions + contributions))
            else
              previous_contribution=$(echo "$previous_contributors" | jq -r --arg login "$login" '.[$login] // 0')
              diff=$((contributions - previous_contribution))
              table+="| @$login | $contributions | +$diff |\n"
            fi
          done

          if [ $bot_contributions -gt 0 ]; then
            table+="| @Github_Actions(Bot) | $bot_contributions | N/A |\n"
          fi

          echo -e "$table" > CONTRIBUTORS.md

          echo "$contributors" | jq -r 'map({(.login): .contributions}) | add' > .github/previous_contributors.json

      - name: 📝 Update README.md
        run: |
          sed -i '/## Contributions des Contributeurs/,$d' README.md
          cat CONTRIBUTORS.md >> README.md

      - name: 📤 Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add README.md .github/previous_contributors.json
            git commit -m "🔄 Mise à jour des contributions des contributeurs"
            git push
          fi

      - name: 🚀 Update branch
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/update_branches.yml/dispatches \
            -d '{"ref":"main"}'
